server:
  servlet:
    context-path: /coding-online/student
  port: 6663

spring:
  profiles:
    active: dev
  security:
    user:
      name: admin@qq.com
      password: 123456
      roles: admin

default_img_path: E:\final\coding-online\student\src\main\resources\static\img\default.jpg
